[build]
  command = "curl -fsSL https://github.com/WebAssembly/binaryen/releases/download/version_101/binaryen-version_101-x86_64-linux.tar.gz --output /tmp/binaryen.tar.gz && tar -xvzf /tmp/binaryen.tar.gz && export PATH=$PATH:/tmp/binaryen-version_101/bin/ && cargo install cargo-make --force && cargo make build_release"

[[headers]]
  for = "/*"

  [headers.values]
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"