[build]
  command = "curl -fsSL https://github.com/WebAssembly/binaryen/releases/download/version_101/binaryen-version_101-x86_64-linux.tar.gz --output $NETLIFY_CACHE_DIR/binaryen.tar.gz && tar -xvzf $NETLIFY_CACHE_DIR/binaryen.tar.gz && export PATH=$PATH:$NETLIFY_CACHE_DIR/binaryen && cargo make build_release"

[[headers]]
  for = "/*"

  [headers.values]
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"